import { ImageResponse } from 'next/og'

/**
 * /brand-logo — a square (512×512) raster of the Krim mark, generated by next/og
 * so structured data (Organization.logo) has a real PNG (Google ignores SVG logos).
 * The mark = the inverted-triangle outline with gaps + centroid dot, in brand mint
 * on the deep canvas. Recreated as <path>/<circle> (satori-native) from
 * public/brand/krim-mark.svg.
 */

export const runtime = 'nodejs'
export const dynamic = 'force-static'

const SIZE = 512

export function GET() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          backgroundColor: '#09090C',
          backgroundImage: 'radial-gradient(50% 50% at 50% 46%, rgba(0,255,178,0.16), rgba(9,9,12,0) 72%)',
        }}
      >
        <svg width="320" height="320" viewBox="0 0 400 400" fill="none">
          <g stroke="#00FFB2" strokeWidth="7" strokeLinecap="round">
            <path d="M100 100 L140 169.3" />
            <path d="M160 203.9 L200 273.2" />
            <path d="M300 100 L260 169.3" />
            <path d="M240 203.9 L200 273.2" />
            <path d="M100 100 L180 100" />
            <path d="M220 100 L300 100" />
          </g>
          <circle cx="200" cy="157.7" r="9" fill="#00FFB2" />
        </svg>
      </div>
    ),
    { width: SIZE, height: SIZE },
  )
}
