/**
 * Asset metadata for the insight imagery — GENERATED by
 * /tmp/optimize_insight_images.py (re-run if the source art changes).
 *
 * Each entry carries the real pixel dimensions (so next/image reserves the
 * correct box, no layout shift) and a tiny inline blur placeholder (a ~20px
 * webp, base64) so the card paints something sharp-feeling instantly while the
 * full image streams in. Used by components/ArticleImage.tsx and the
 * /insights preview grid.
 */

export type CinematicMeta = { w: number; h: number; blur: string }

export const CINEMATIC: Record<string, CinematicMeta> = {
  '/images/cinematic/sovereignty.webp': { w: 1200, h: 1789, blur: 'data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBQCdASoUAB4APwFyr1ArJyQisBgIAWAgCWwAnTNnxAAXOvU9LqDkWIYDbNWB1KM4XLIAAP7wvfLibDTaMcJ7dE45oe+k3OU/kt+KEz3E8DGOwNpFr/LfP1wJYpjUwF48xBbChZIfeZuaCqlN6RPJEwvCaiDqxmaObH/iDWXcd3VbfVeAWT/+k8PMWpqBGx9CsSB9SsAmdziUq9wT8xfEwZp9WwCEvywAAA==' },
  '/images/cinematic/audit.webp': { w: 1200, h: 1789, blur: 'data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADQBACdASoUAB4APu1ep06ppSOiN/qoATAdiWQApxQh3+DqyWCx/g+Kkn4ZtIQygAD+8qBymqxVbNTNV09pY2J3BwrBB4xsdXJ9vHGo+vvexRe0laFumPa2D4svihLg+1WLwqJ3yDIbiKohY09yu0UGyjj8RLTk+KpcdLX2aKYz5rt0w/6orxJzkeVzexVucNiiDKBnQAA=' },
  '/images/cinematic/credit-gap.webp': { w: 1200, h: 1789, blur: 'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwBACdASoUAB4APvFkrU6ppaSiMAwBMB4JaAC2yCHf7y7b4GxJr7VIDx0odcUAPEAA/vKeY5ap3KIderLXAMS763cGpoD7mkx2gN9wsYf9CNtvvoCMrwxEDqJZVKBPS01ldw8OFlHGm1V+6w2KkDYB+HN3RJHVdx3AOyAA' },
  '/images/cinematic/automation-gap.webp': { w: 1200, h: 1789, blur: 'data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwBACdASoUAB4APwFsrlArJiQiqA1RYCAJQBdgCLv4Cwa288C4B5LYNYwYMAD+93FkdWwGdn0nZr2xWGzsNxziMZcPtn8XMjC4S2NgnxE5cwomIshO5nu/59C4L+VmDXrVP4NG0ircAANVwfNi3A28e7dQAA==' },
  '/images/cinematic/insight-wave.jpg': { w: 864, h: 1296, blur: 'data:image/webp;base64,UklGRv4AAABXRUJQVlA4IPIAAABwBQCdASoUAB4APwForE6rJaQiMAgBYCAJZwDKAxUFOB72Dykgde4nnsCKLBUCEIj0K6GwAP5NO6GovlLh32uSZVFsfe0oZfI2FLyNcWJ6RaTiBti5Crb+HdjtavztE24FxMlzIsVdBCp/r162cS+u+6kx2Or44E3Gqy0C9RAxt4Hz3NKGbUqFQyif1uW8nqMcpPxlbnbqfn84hC47IEcrNrWfs/UoIBMbJbEREga5bHoyxdNDT6jpPi17UrhTiwC2MF89kdFigrG8EH+0T1D+yDVWOXJgDE02RKIiTIqt3H9wXpj1eit9JlKs9Z+t0P2AAA==' },
  '/images/cinematic/architecture-lattice.jpg': { w: 1137, h: 1600, blur: 'data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAAAQBQCdASoUABwAPwFys1GrJqSiqAqpYCAJYwCw7Am1yoJQnVf+CjjeMleaGbYNRNIAAP7Z9gArhLrHPpuCSmv9Mg90/XYiNwnO48QypcLsjt2GVQrMmP+0jVI+DHZPFSD3iFXxCdvLYQmiLJ/Pje/r8nujZm8LdmhDYALuwB5NNcscWDkLpT2Wj6Qp/eooGZUBPTZsO1S8KSywz43iV0UTZRFOZ6g8dpheEnjFbMvi8DiWj84z6O3CgcqBHmu5YOAAAA==' },
}
