#!/usr/bin/env python3
"""
Committed image pipeline — the single, repeatable way site imagery is optimised.
Run:  npm run images:optimize   (or: python3 scripts/optimize_images.py)

For every asset in MANIFEST it:
  - if `src_from` is set, reads that heavy source, downscales it to `max_w`
    (never upscales, preserves alpha), and writes a compact .webp at `web`
    — so even the first optimiser/CDN hit serves a small file, not a 3MB PNG;
  - always records the REAL pixel width/height (so next/image reserves the
    correct box → no layout shift) and a tiny ~24px base64 LQIP blur (so the
    image paints something sharp-feeling instantly while the full one streams).

It writes lib/image-manifest.ts (keyed by the public path referenced in JSX).
Add a new image here, run the script, and it is correct by construction.

Supersedes the throwaway /tmp/optimize_insight_images.py that only knew about
/images/cinematic.
"""

import base64
import io
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC = os.path.join(ROOT, "public")
OUT_TS = os.path.join(ROOT, "lib", "image-manifest.ts")

LQIP_WIDTH = 24
LQIP_QUALITY = 42

# `web` is the path referenced in JSX. `src_from` (optional) is a heavy source
# that gets downscaled + re-encoded into `web`. Entries without `src_from` are
# already web-sized; we only record their dimensions + blur.
MANIFEST = [
    # Heavy PNG heroes → pre-shrunk compact webp (3.4MB → ~100KB).
    {"web": "/images/harness/harness-gate.webp",
     "src_from": "/images/harness/harness-gate.png", "max_w": 1000, "quality": 82},

    # Already-optimised cinematic art — record metadata only.
    {"web": "/images/cinematic/world-model.webp"},
    {"web": "/images/cinematic/sovereignty.webp"},
    {"web": "/images/cinematic/audit.webp"},
    {"web": "/images/cinematic/credit-gap.webp"},
    {"web": "/images/cinematic/automation-gap.webp"},
    {"web": "/images/cinematic/insight-wave.jpg"},
    {"web": "/images/cinematic/architecture-lattice.jpg"},
]


def public_path(web: str) -> str:
    return os.path.join(PUBLIC, web.lstrip("/"))


def lqip(img: Image.Image) -> str:
    w, h = img.size
    small = img.copy()
    small.thumbnail((LQIP_WIDTH, max(1, round(LQIP_WIDTH * h / w))), Image.LANCZOS)
    buf = io.BytesIO()
    small.convert("RGBA" if small.mode in ("RGBA", "LA", "P") else "RGB").save(
        buf, "WEBP", quality=LQIP_QUALITY, method=6
    )
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def process(entry: dict) -> dict:
    web = entry["web"]
    dest = public_path(web)

    if entry.get("src_from"):
        src = public_path(entry["src_from"])
        if not os.path.exists(src):
            raise SystemExit(f"missing source: {entry['src_from']}")
        img = Image.open(src)
        max_w = entry["max_w"]
        if img.width > max_w:
            img = img.resize((max_w, round(img.height * max_w / img.width)), Image.LANCZOS)
        save = img
        if img.mode not in ("RGB", "RGBA"):
            save = img.convert("RGBA" if "A" in img.mode or img.mode == "P" else "RGB")
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        save.save(dest, "WEBP", quality=entry["quality"], method=6)
        kb = os.path.getsize(dest) / 1024
        print(f"  emitted {web}  {save.width}x{save.height}  {kb:.0f}KB")
    elif not os.path.exists(dest):
        raise SystemExit(f"missing file: {web}")

    with Image.open(dest) as im:
        w, h = im.size
        blur = lqip(im)
    return {"web": web, "w": w, "h": h, "blur": blur}


def main() -> None:
    entries = [process(e) for e in MANIFEST]
    body = "\n".join(
        f"  '{e['web']}': {{ w: {e['w']}, h: {e['h']}, blur: '{e['blur']}' }},"
        for e in entries
    )
    ts = (
        "/**\n"
        " * GENERATED by scripts/optimize_images.py — do not edit by hand.\n"
        " * Run `npm run images:optimize` after adding or changing any site image.\n"
        " *\n"
        " * Keyed by the public path referenced in JSX. Each entry carries the real\n"
        " * pixel dimensions (next/image reserves the correct box → no layout shift)\n"
        " * and a tiny inline LQIP blur (paints instantly while the full image streams).\n"
        " */\n\n"
        "export type ImageMeta = { w: number; h: number; blur: string }\n\n"
        "export const IMAGE_MANIFEST: Record<string, ImageMeta> = {\n"
        f"{body}\n"
        "}\n\n"
        "/** Legacy alias — existing imports of CINEMATIC keep working. */\n"
        "export const CINEMATIC = IMAGE_MANIFEST\n"
    )
    with open(OUT_TS, "w") as f:
        f.write(ts)
    print(f"\n  wrote {len(entries)} entries -> lib/image-manifest.ts")


if __name__ == "__main__":
    main()
